### PR TITLE
Allow using interfaces to declare repository in Entity attribute

### PR DESCRIPTION
**Pull request by roquie**
An interface is better than a concrete object for testing and supporting multiple databases

### CODE REVIEW

**Comment by butschster** [comment]
Hi @roquie!

Thank you for PR! Could you please put an example of code for the feature?

**Comment by roxblnfk** [comment]
Need to test it.

**Comment by roxblnfk** [comment]
@butschster 

- [ ] cover with tests
- [ ] add description

**Comment by butschster** [comment]
@see #40

**Pull request closed without merging**
